version: '3'

services:
  netflix-movie-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netflix-movie-backend-ct
    env_file:
          - .env
    ports:
      - '5001:5000'

  netflix-movie-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netflix-movie-frontend-ct
    ports:
      - '3001:3000'
    volumes:
      - ./frontend/src:/app/src   
    depends_on:
      - netflix-movie-backend
